# Generated by Django 2.1.7 on 2019-03-31 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='receive_time',
            field=models.TimeField(default=datetime.time(14, 3, 8, 95987), verbose_name='Время получения сообщения'),
        ),
    ]
